#!/usr/bin/python
import sys
import datetime
from typing import List

template = """# {date}

## Daily checklist

* [ ] Take a vitamin C
* [ ] Eat your daily carrot!

## Todo

## Notes"""


def add_title(document: List[str], title: str, level: int) -> List[str]:
    return document + [f"{'#' * level} {title}"]


date = (
    datetime.date.today()
    if len(sys.argv) < 2
    # Expecting filename in YYYY-MM-DD.foo format
    else sys.argv[1].rsplit(".", 1)[0]
)
print(template.format(date=date))
