-- ---@type overseer.TemplateFileProvider
-- return {
--   {
--     name = "Install",
--     desc = "Runs `pip install` in the current working directory",
--     condition = {
--       filetype = { "python" },
--     },
--     builder = function ()
--       return {
--         cmd = { "pip" , "install", vim.uv.cwd()}
--       }
--     end
--   }
-- 
-- }
