# Options
set-option -sa terminal-overrides ",xterm*:RGB"
set -g mouse on
set -g status-position top

# Theming
set-option -g status-style "bg=default,fg=gold"
set -g @catppuccin_flavor "frappe"
set -g @catppuccin_window_status_style "rounded"

run '~/.tmux/plugins/tmux/catppuccin.tmux'

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

## Window & Pane numbering
set -g base-index 1
set -g pane-base-index 1
set-option -g status-interval 5
set-option -g automatic-rename off
set-option -g automatic-rename-format '#{b:pane_current_path}'

set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_text "#W"

set-window-option -g pane-base-index 1
set-option -g renumber-windows on

## Session management
set -g detach-on-destroy off

# Remove SSH_AUTH_SOCK to disable tmux automatically resetting the variable
set -g update-environment "DISPLAY SSH_ASKPASS SSH_AGENT_PID \
                             SSH_CONNECTION WINDOWID XAUTHORITY"

# Use a symlink to look up SSH authentication
setenv -g SSH_AUTH_SOCK $HOME/.ssh/ssh_auth_sock


## Disable annoying sounds
set-option -g bell-action none
set-option -g visual-bell off

## Passtrhoug
set -g allow-passthrough on

## Yanking stuff
set-window-option -g mode-keys vi

# Keybindings
unbind        C-b
set-option    -g prefix C-a

## Keymap
bind      -n                C-S-P previous-window
bind      -n                C-S-N next-window

bind-key                    C-a   send-prefix
bind-key  -T  prefix        x     kill-pane
bind-key  -T  prefix        X     kill-window
bind-key  -T  copy-mode-vi  v     send-keys     -X begin-selection
bind-key  -T  copy-mode-vi  C-v   send-keys     -X rectangle-toggle
bind-key  -T  copy-mode-vi  y     send-keys     -X copy-selection-and-cancel

bind-key                    h     split-window  -v  -c '#{pane_current_path}'
bind-key                    v     split-window  -h  -c '#{pane_current_path}'
bind-key                    c     new-window        -c '#{pane_current_path}'

## Popups
bind-key                    P     display-popup -d '#{pane_current_path}' -w 80% -h 80% 
bind-key                    G     display-popup -d '#{pane_current_path}' -w 80% -h 80% -E "lazygit"
bind-key                    B     display-popup -d '#{pane_current_path}' -w 80% -h 80% -E "btop"

### Sesh binding
bind-key "S" run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'ctrl-j:down,ctrl-k:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""

bind-key "W"  run-shell "~/.config/userscripts/tmux_management.sh -w"
bind     "N"  run-shell "~/.config/userscripts/tmux_management.sh -c"

### return to last session
bind -N "last-session (via sesh) " L run-shell "sesh last"
### Connect to root
bind -N "switch to root session (via sesh) " 9 run-shell "sesh connect --root $(pwd)"

# Installing Plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'

run 'tpack init'
