#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json

sort_order = [
  "🏠 Home",
  "🌍 Devinite",   # show first
  "📔 BookIn",
  "🚚 Logistics",
  "👨‍💻 dotfiles",
]

[[window]]
name = " Editor"
startup_script = "nvim"

[[window]]
name = "󰚩 OpenCode"
startup_script = "opencode"

[[session]]
name = "🏠 Home"
path = "~"
preview_command = "ls ~"

[[session]]
name = "🌍 Devinite"
path = "~/Projects/devinite/master"
preview_command = "bat --color=always ~/c/Projects/devinite/master/README.md"
windows = [" Editor", "󰚩 OpenCode"]

[[session]]
name = "📔 BookIn"
path = "~/Projects/Dg.BookIn/master"
preview_command = "bat --color=always ~/Projects/Dg.BookIn/master/README.md"
windows = [" Editor", "󰚩 OpenCode"]

[[session]]
name = "🚚 Logistics"
path = "~/Projects/Dg.Logistics/master"
preview_command = "bat --color=always ~/Projects/Dg.Logistics/master/README.md"
windows = [" Editor", "󰚩 OpenCode"]

[[session]]
name = "📮 Receiving"
path = "~/Projects/Dg.Receiving/master"
preview_command = "bat --color=always ~/Projects/Dg.Receiving/master/README.md"
windows = [" Editor", "󰚩 OpenCode"]

[[session]]
name = "🏪 Warehousing"
path = "~/Projects/Dg.Warehousing/master"
preview_command = "bat --color=always ~/Projects/Dg.Warehousing/master/README.md"
windows = [" Editor", "󰚩 OpenCode"]

[[session]]
name = "🔄 Automatic Counting"
path = "~/Projects/Dg.BookIn.AutomaticCounting/master"
preview_command = "bat --color=always {}/README.md"
windows = [" Editor", "󰚩 OpenCode"]

[[session]]
name = "👨‍💻 dotfiles"
path = "~/Projects/.dotfiles/"
preview_command = "bat --color=always ~/Projects/dotfiles/README.md"
windows = ["👨‍💻 dotfiles", "🤖 AiAgents"]

[[window]]
name = "👨‍💻 dotfiles"
path = "~/Projects/.dotfiles/"
startup_script = "nvim"

[[window]]
name = "🤖 AiAgents"
path = "~/Projects/AiAgents/"
startup_script = "nvim"

[[session]]
name = "󰣀 Raspi Home"
path = "~/"
startup_command = "ssh patrick@raspberrypi.local"

[[session]]
name = "󰣀 Counter Camera"
path = "~/"
startup_command = "ssh counter@cc-g1-d1"

[[wildcard]]
pattern = "~/Projects/*"
preview_command = "ls {}"
disable_startup_command = false
windows = [" Editor", "󰚩 OpenCode"]
